resource_group_name    = "rootnyc_terraform_rg"
location               = "West Europe"
keyvault_name          = "harithasecretkey"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"
